func = { SOI ~ expr ~ EOI }
expr = { add }
add = { mul ~ (add_sign ~ mul)* }
mul = { neg ~ (mul_sign ~ neg)* }
neg = { "-"? ~ exp }
exp = { primary ~ ("^" ~ primary )* }
primary = { call_1 | var | constant | "(" ~ expr ~ ")" }
call_1 = { name ~ primary }
var = { "t" }
constant = @{ "-"? ~ ASCII_DIGIT+ ~ ("." ~ ASCII_DIGIT+)? }

name = @{ ASCII_ALPHA ~ ASCII_ALPHANUMERIC* }
mul_sign = { "*" | "/" }
add_sign = { "+" | "-" }

WHITESPACE = _{ " " }